#gcc eg1.c -l dbus-1 -I/usr/local/include/dbus-1.0   -I/usr/include/dbus-1.0/ -I/usr/include/glib-2.0  -I/usr/lib/x86_64-linux-gnu/glib-2.0/include/ -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include/^C


CC = gcc
CXX = g++
CFLAGS = -Wno-psabi -fstack-protector-all -fno-omit-frame-pointer -g -march=armv5te -marm -mthumb-interwork -mtune=arm926ej-s -DLINUX=1 -DEGL_API_FB=1 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH =  -I/usr/local/include/dbus-1.0   -I/usr/include/dbus-1.0/ -I/usr/include/glib-2.0  -I/usr/lib/x86_64-linux-gnu/glib-2.0/include/ -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include/