/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static inline void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_wei_MyObject_Sample
#define DBUS_GLIB_CLIENT_WRAPPERS_com_wei_MyObject_Sample

static inline gboolean
com_wei_MyObject_Sample_test (DBusGProxy *proxy, const guint IN_x, gdouble* OUT_d_ret, GError **error)

{
  return dbus_g_proxy_call (proxy, "Test", error, G_TYPE_UINT, IN_x, G_TYPE_INVALID, G_TYPE_DOUBLE, OUT_d_ret, G_TYPE_INVALID);
}

typedef void (*com_wei_MyObject_Sample_test_reply) (DBusGProxy *proxy, gdouble OUT_d_ret, GError *error, gpointer userdata);

static void
com_wei_MyObject_Sample_test_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gdouble OUT_d_ret;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_DOUBLE, &OUT_d_ret, G_TYPE_INVALID);
  (*(com_wei_MyObject_Sample_test_reply)data->cb) (proxy, OUT_d_ret, error, data->userdata);
  return;
}

static inline DBusGProxyCall*
com_wei_MyObject_Sample_test_async (DBusGProxy *proxy, const guint IN_x, com_wei_MyObject_Sample_test_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Test", com_wei_MyObject_Sample_test_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_UINT, IN_x, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_wei_MyObject_Sample */

G_END_DECLS
